import type { Context } from "hono";
import type { DB, DbSchema, Dialect } from "./db";
import type { Role } from "@shared/types";

/**
 * Runtime bindings. `Env` is generated by `wrangler types` (worker-configuration.d.ts)
 * and contains HYPERDRIVE, LINKS_KV, ASSETS and APP_URL. Secrets are added here.
 */
export interface AppBindings extends Env {
  SESSION_SECRET: string;
  /** One-time bootstrap token gating the first-run installer (`POST /api/setup`). */
  SETUP_TOKEN: string;
  /** NOTE: `PBKDF2_ITERATIONS` (deploy-time PBKDF2 cost, default "20000") is a
   *  wrangler var, so it is already part of the generated `Env` and inherited
   *  here — it is intentionally NOT redeclared. `wrangler types` emits it as the
   *  literal `"20000"`, and widening it to `string` here breaks `extends Env`
   *  (TS2430). Read + clamped by `pbkdf2Iterations()`; see worker/lib/password.ts. */
  /** Hyperdrive (Postgres) binding, present only when DB_DRIVER="postgres" and the
   *  `hyperdrive` block in wrangler.jsonc is uncommented (otherwise absent from the
   *  generated Env, so it's declared optional here). With the default DB_DRIVER="d1"
   *  the `DB` (D1) binding comes straight from the generated Env (required); to
   *  switch to Postgres, uncomment hyperdrive in wrangler.jsonc and add
   *  `DB?: D1Database` back here. DB_DRIVER itself comes from the generated Env (a
   *  wrangler var). Cloudflare-for-SaaS custom domain credentials live in settings
   *  (configured via /admin), not env. */
  HYPERDRIVE?: Hyperdrive;
  /** NOTE: `RATE_LIMITER` (exact rate-limit Durable Object, Phase F) is a wrangler
   *  binding, so it is in the generated `Env` and inherited here — NOT redeclared.
   *  `wrangler types` types it as `DurableObjectNamespace<RateLimiter>` (required);
   *  redeclaring it optional/untyped breaks `extends Env` (TS2430). It is treated
   *  as optional at runtime (deploys without it fall back to the KV limiter) via a
   *  cast in `worker/lib/ratelimit.ts` (`env.RATE_LIMITER ?? null`). */
}

export interface SessionUser {
  id: string;
  email: string;
  role: Role;
}

export interface AppVariables {
  db: DB;
  schema: DbSchema;
  dialect: Dialect;
  user: SessionUser | null;
  sessionId: string | null;
}

export type AppEnv = { Bindings: AppBindings; Variables: AppVariables };
export type AppContext = Context<AppEnv>;
